version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
  backend:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - 'mongodb'
volumes:
  data:
